version: "3.8"

services:
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=tsunami
    volumes:
      - timescaledb:/var/lib/postgresql/data
    networks:
      - timescaledb

  timescaledbsetup:
    container_name: dbsetup
    image: timescale/timescaledb:latest-pg12
    depends_on:
      - timescaledb
    networks:
      - timescaledb
    entrypoint: ["psql -U postgres && "]

volumes:
  timescaledb:
    external: true
networks:
  timescaledb:
    external: true
#  mongosetup:
#     image: mongo:4.2.8
#     depends_on:
#       - mongo
#     restart: "no"
#     entrypoint: [ "bash", "-c", "sleep 10 && mongo --host mongo:27017 --eval 'rs.initiate()'"]
