version: "3.8"

services:
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=tsunami
    volumes:
      - timescaledb:/var/lib/postgresql/data
      - /Users/galois/docker/dev/dev_sql:/home/dev_sql
    networks:
      - timescaledb

  timescaledbsetup:
    container_name: tsdbsetup
    image: timescale/timescaledb:latest-pg12
    depends_on:
      - timescaledb
    networks:
      - timescaledb
    entrypoint: ["psql -U postgres -h 127.0.0.1 -p 5432 -f /home/dev_sql/tsdbinit.sql"]

volumes:
  timescaledb:
    external: true
networks:
  timescaledb:
    external: true
