version: "3.8"

services:
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=tsunami
      - DB_HOST_NAME=timescaledb
    volumes:
      - timescaledb:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql #create tables and 'financial' database
    networks:
      - timescaledb

  snapshot:
    container_name: snapshot
    image: polysnap-node:testing
    depends_on:
      - timescaledb
    ports:
      - 4005:4005
    networks:
      - timescaledb

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - timescaledb
    environment:
      - POSTGRES_PASSWORD=tsunami
      - DB_HOST_NAME=timescaledb
      - GF_SECURITY_ADMIN_USER=admin_user
      - GF_SECURITY_ADMIN_PASSWORD=admin_password
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=timescaledb:5432
      - GF_DATABASE_NAME=financial
      - GF_DATABASE_USER=postgres
      - GF_DATABASE_PASSWORD=tsunami
    networks:
      - timescaledb
    volumes:
      - grafana-storage:/var/lib/grafana
    command: bash -c 'while !</dev/tcp/db/5432; do echo 'PG is NA' sleep 1; done; sh /run.sh'

volumes:
  timescaledb:
    external: true
  grafana-storage:
    external: true
networks:
  timescaledb:
    external: true
