version: "3.8"

services:
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=tsunami
    volumes:
      - timescaledb:/var/lib/postgresql/data
    networks:
      - timescaledb

  timescaledbsetup:
    container_name: tsdbsetup
    image: timescale/timescaledb:latest-pg12
    depends_on:
      - timescaledb
    volumes:
      - /Users/galois/docker/dev/dev_sql:/usr/src/app
    networks:
      - timescaledb
    entrypoint: ["sh", "/usr/src/app/init.sh"]

volumes:
  timescaledb:
    external: true
networks:
  timescaledb:
    external: true
